services:
  catalog:
    image: catalog
    build:
      context: ./catalog
      dockerfile: Dockerfile
    container_name: catalog
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
    restart: "no"

  # TODO: Add your gateway service here
  # gateway:
  #   image: gateway
  #   build:
  #     context: ???
  #     dockerfile: ???
  #   container_name: gateway
  #   ports:
  #     - "???:???"
  #   environment:
  #     - PORT=???
  #     - CATALOG_URL=???
  #   restart: "no"
